[package]
name = "transakt"
version = "0.1.0"
authors = ["Petre Eftime <petre.eftime@gmail.com>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1"
serde = { version = "1", features = ["derive"] }
log = "0.4"
env_logger = "0.8"
